version: '3.9'
services:
  backend:
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@postgres/database
    depends_on:
      - "liquibase"
    links:
      - "liquibase:liquibase"
    build: ./backend

  frontend:
    build: ./frontend
    ports:
      - '3010:3000'
    environment:
      REACT_APP_BACKEND_URL_PORT: "localhost:8080"
    links:
      - "backend"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d database"]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/resources/:/liquibase/changelog/
    command: --url=jdbc:postgresql://postgres:5432/database?user=user&password=password --changeLogFile=changelog.xml update