version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user@postgres/database

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: database
